

services :
  cache:
    image: valkey/valkey:latest
    container_name: hivebox-cache
    ports:
      - "6379:6379"
  storage:
    image: minio/minio:latest
    container_name: hivebox-storage
    ports:
      - "9000:9000" # API Port
      - "9001:9001" # Console Port
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"