apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  replicas: {{ .Values.replicaCount }} # Pulls '2' from values.yaml
  selector:
    matchLabels:
      app: hivebox
  template:
    metadata:
      labels:
        app: hivebox
    spec:
      containers:
        - name: hivebox
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 3000
          # --- THE READINESS PROBE ---
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readinessPath }}
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10