apiVersion: apps/v1
kind: Deployment
metadata:
  name: hivebox-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hivebox
  template:
    metadata:
      labels:
        app: hivebox
    spec:
      containers:
      - name: hivebox-container
       
        image: localhost:5000/hivebox:test:v2
        envFrom:
        - configMapRef:
            name: hivebox-config
        
        
        imagePullPolicy: Always
        
        ports:
        
        - containerPort: 3000

        readinessProbe:
          httpGet:
            path: /readyz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10


          
        