apiVersion: v1
kind: Service
metadata:
  name: hivebox-service
spec:
  selector:
    app: hivebox
  ports:
    - protocol: TCP
      port: 80        # The Service listens on port 80...
      targetPort: 3000 # ...and forwards traffic to port 3000 on the container.