apiVersion: v1
kind: Service
metadata:
  name: valkey-service
spec:
  selector:
    app: valkey # This matches the label in our Deployment!
  ports:
    - protocol: TCP
      port: 6379       # The port other pods use to talk to this service
      targetPort: 6379  # The port inside the Valkey container