name : CI Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
# # permissions for ossf
#     permissions:
#       contents: read
#       security-events: write
#       id-token: write


    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Install lint
        run: npm run lint

      - name: Unit Test 
        run: npm test
      
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      
      - name: Build Docker Image
        run: docker build . -t hivebox:test

      - name: Run Docker Container 
        run: docker run -d -p 3000:3000 --name test-container hivebox:test

      - name: Wait for App to start
        run: sleep 10

      - name: Test Version endpoint
        run: |
            # 1. Call the endpoint and capture the output
            RESPONSE=$(curl -s http://localhost:3000/version)
            
            # 2. Print the response so we can see it in the logs
            echo "Server responded with: $RESPONSE"
            
            # 3. Check if the response contains "1.0.0" (or your current version)
            if [[ "$RESPONSE" == *"1.0.0"* ]]; then
              echo "✅ Version check passed!"
              exit 0
            else
              echo "❌ Version check failed! Expected '1.0.0' but got '$RESPONSE'"
              exit 1
            fi
      - name: Debug - Show Container Logs
        run: docker logs test-container


      # - name: OpenSSf Scorecard
      #   uses: ossf/scorecard-action@v2.4.0
      #   with:
      #     results_file: results.sarif
      #     results_format : sarif
      #     publish_results : true
  scorecard:
    runs-on: ubuntu-latest
    permissions:
      # specific permissions needed for scorecard
      security-events: write
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: OpenSSF Scorecard
        uses: ossf/scorecard-action@v2.4.0
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

