name : CI Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
# # permissions for ossf
#     permissions:
#       contents: read
#       security-events: write
#       id-token: write


    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Install lint
        run: npm run lint

      - name: Unit Test 
        run: npm test
      
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      
      - name: Build Docker Image
        run: docker build . -t hivebox:test

      - name: Run Docker Container 
        run: docker run -d -p 3000:3000 --name test-container hivebox:test

      - name: Wait for App to start
        run: sleep 10

      - name: Debug - Show Container Logs
        run: docker logs test-container

      - name: Simple version checkout
        run: |
            #0 get rid of old container if there
            docker rm -f test-container || true
            #1 start container in the back
            docker run -d -p 3000:3000 --name test-container hivebox:test

            #2 wait a bit
            sleep 5

            #Ask for the version
            curl -f http://localhost:3000/version 


      # - name: Test Version endpoint
      #   run: |
      #     # 1. Extract the expected version from package.json
      #     EXPECTED_VERSION=$(jq -r .version package.json)
      #     echo "Target version from package.json: $EXPECTED_VERSION"
          
      #     # 2. Call the endpoint
      #     RESPONSE=$(curl -s http://localhost:3000/version)
      #     echo "Actual server response: $RESPONSE"
          
      #     # 3. Compare them
      #     if [[ "$RESPONSE" == *"$EXPECTED_VERSION"* ]]; then
      #       echo "✅ Success! The endpoint matches package.json."
      #       exit 0
      #     else
      #       echo "❌ Mismatch! Expected '$EXPECTED_VERSION' inside response."
      #       exit 1
      #     fi
      


      # - name: OpenSSf Scorecard
      #   uses: ossf/scorecard-action@v2.4.0
      #   with:
      #     results_file: results.sarif
      #     results_format : sarif
      #     publish_results : true
  scorecard:
    runs-on: ubuntu-latest
    permissions:
      # specific permissions needed for scorecard
      security-events: write
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: OpenSSF Scorecard
        uses: ossf/scorecard-action@v2.4.0
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

