name : CI Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
# # permissions for ossf
#     permissions:
#       contents: read
#       security-events: write
#       id-token: write


    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Install lint
        run: npm run lint

      - name: Run Terrascan
        id: terrascan
        uses: tenable/terrascan-action@main
        with:
          iac_type: 'k8s'
          iac_version: 'v1'
          policy_type: 'k8s'
          only_warn: false # Builds will now fail on errors
          iac_dir: 'k8s'

      - name: Tests 
        run: npm test

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@v4
        env:
          # We need to pass the Token and Host URL here
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
      
      - name: Build Docker Image
        run: docker build . -t hivebox:test

      - name: Run Docker Container 
        run: docker run -d -p 3000:3000 --name test-container hivebox:test

      - name: Wait for App to start
        run: npx wait-on http://localhost:3000

      - name: Debug - Show Container Logs
        run: docker logs test-container

      - name: Simple version checkout
        run: |
            #0 get rid of old container if there
            docker rm -f test-container || true
            #1 start container in the back
            # 1. start container with the Environment Variable
            docker run -d \
            -p 3000:3000 \
            -e SENSEBOX_ID="606b20a3b8e635001b80a306" \
            --name test-container \
            hivebox:test

            #2 wait a bit
            sleep 5

            #Ask for the version
            curl -f http://localhost:3000/version 


      # - name: Test Version endpoint
      #   run: |
      #     # 1. Extract the expected version from package.json
      #     EXPECTED_VERSION=$(jq -r .version package.json)
      #     echo "Target version from package.json: $EXPECTED_VERSION"
          
      #     # 2. Call the endpoint
      #     RESPONSE=$(curl -s http://localhost:3000/version)
      #     echo "Actual server response: $RESPONSE"
          
      #     # 3. Compare them
      #     if [[ "$RESPONSE" == *"$EXPECTED_VERSION"* ]]; then
      #       echo "✅ Success! The endpoint matches package.json."
      #       exit 0
      #     else
      #       echo "❌ Mismatch! Expected '$EXPECTED_VERSION' inside response."
      #       exit 1
      #     fi
      


      # - name: OpenSSf Scorecard
      #   uses: ossf/scorecard-action@v2.4.0
      #   with:
      #     results_file: results.sarif
      #     results_format : sarif
      #     publish_results : true
  scorecard:
    runs-on: ubuntu-latest
    permissions:
      # specific permissions needed for scorecard
      security-events: write
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: OpenSSF Scorecard
        uses: ossf/scorecard-action@v2.4.0
        with:
          results_file: results.sarif
          results_format: sarif
          publish_results: true

